/**
 * The twelfth demo, judged from the documents' side.
 *
 * ## What this file can hold and what it cannot
 *
 * `examples/vscode-cockpit` judges the **compiled Cockpit**, and its subject is therefore a build
 * product: `extension/vscode/out/` is generated by `npm run build`, and the root gate does not build
 * it - the root `tsconfig.json` excludes `extension/**`, and this tree's suite runs the `.ts` source
 * directly. So a test here that staged the artifact and ran the world would have to skip whenever the
 * extension had not been built, and a skipped test does not fail - it silently reduces coverage while
 * reporting a green suite.
 *
 * The reading about behaviour is therefore taken by `demo.ts`, which refuses by name when `out/` is
 * absent and says which command produces it. What this file holds instead is the set of claims the
 * demo's own documents make about one another, none of which needs a build:
 *
 * - `acceptance.yaml` pins the identity of the extension it judges, and `extension/vscode/package.json`
 *   declares that identity. Those are the same claim written twice, and the first occurrence of the
 *   drift this file exists to prevent was real: the contract said `0.2.1` while the artifact under test
 *   had become `0.2.2`, which would have failed a correct extension and sent a reader to inspect the
 *   one thing that was not broken.
 * - `cli/worlds.ts` declares which pointers the `sim-vscode` world requires, and `environment.yaml`
 *   states them. The requirement is a *place*, so it is resolved as a pointer rather than read as a
 *   literal key - the defect this repository has already paid for once.
 * - The two vocabularies a contract can get wrong from a distance: the validator names it uses, and the
 *   evidence kinds it asks for. Neither is checked by reading the contract; both are checked against
 *   the code that has to answer them.
 * - `app/provision.mjs` reads four environment names, and the adapter declares the names it will set.
 *   The two files must agree, and a list recalled in a test is a claim about two files that nothing
 *   reconciles - so both sets are read out of their own source.
 * - The staged extension directory is generated, and a generated tree that is not ignored is one
 *   `git add .` away from being committed.
 */

import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { describe, it } from "node:test";

import { parse } from "yaml";

import { findWorld } from "../cli/worlds.ts";
import { allValidators } from "../cli/validators.ts";

const read = (path: string): string => readFileSync(new URL(`../${path}`, import.meta.url), "utf8");

/** A record, or an empty one. Narrowing rather than casting, so a wrong shape fails a later assertion. */
function record(value: unknown): Record<string, unknown> {
  if (typeof value !== "object" || value === null) return {};
  return value as Record<string, unknown>;
}

/** The members of an array, or none. */
function array(value: unknown): readonly unknown[] {
  return Array.isArray(value) ? value : [];
}

const DEMO = "examples/vscode-cockpit";
const ADAPTER = "sim-vscode";

const contract = record(parse(read(`${DEMO}/acceptance.yaml`)));
const goal = record(parse(read(`${DEMO}/goal.yaml`)));
const environment = record(parse(read(`${DEMO}/environment.yaml`)));
const criteria = array(contract.criteria).map(record);

/** Every `expect` entry in the contract, flattened, with the criterion it belongs to. */
const expectations = criteria.flatMap((criterion) =>
  array(criterion.expect).map((entry) => ({ criterion, entry: record(entry) })),
);

/** The validator names the contract names, derived rather than written down here. */
const namedValidators = [
  ...new Set(
    expectations
      .map(({ entry }) => entry.validator)
      .filter((name): name is string => typeof name === "string"),
  ),
];

/** The evidence kinds the contract asks for, derived rather than written down here. */
const namedEvidence = [
  ...new Set(
    criteria.flatMap((criterion) =>
      array(criterion.evidence).filter((kind): kind is string => typeof kind === "string"),
    ),
  ),
].sort();

/** Resolve a dot path as a pointer, which is how the ladder reads a requirement. */
function pointer(document: Record<string, unknown>, path: string): unknown {
  let at: unknown = document;
  for (const segment of path.split(".")) {
    if (typeof at !== "object" || at === null) return undefined;
    at = (at as Record<string, unknown>)[segment];
  }
  return at;
}

describe("the vscode-cockpit demo's documents", () => {
  it("pins the identity the Cockpit's own manifest declares", () => {
    const manifest = record(JSON.parse(read("extension/vscode/package.json")));
    const name = manifest.name;
    const version = manifest.version;
    assert.equal(typeof name, "string", "the Cockpit's manifest declares no name");
    assert.equal(typeof version, "string", "the Cockpit's manifest declares no version");

    const identity = expectations.find(({ entry }) => entry.validator === "vscode.identity");
    assert.ok(identity, "the contract names no vscode.identity expectation");
    const pinned = identity.entry.contains;
    if (typeof pinned !== "string") assert.fail("the vscode.identity expectation compares with no value");

    assert.ok(
      pinned.includes(`${String(name)} ${String(version)}`),
      `the contract pins "${pinned}", and the extension this demo stages declares ` +
        `"${String(name)} ${String(version)}" - so the run would judge the artifact it claims to ` +
        `judge only by accident. Bumping the version means moving this expectation in the same pass.`,
    );
  });

  it("names only validators the registry holds", () => {
    const registered = new Set(allValidators().map((validator) => validator.name));
    assert.ok(namedValidators.length > 0, "the contract exercises no validator at all");
    const unknown = namedValidators.filter((name) => !registered.has(name));
    assert.deepEqual(
      unknown,
      [],
      `the contract names ${unknown.join(", ")}, which no registered validator answers - so every ` +
        `criterion over them is INCONCLUSIVE however correct the extension is`,
    );
  });

  it("asks for evidence kinds the world can write", () => {
    assert.deepEqual(
      namedEvidence,
      ["json"],
      "the extension-host world writes `json` and nothing else: there is no page to screenshot, and " +
        "`snapshot-restore` is refused by name rather than downgraded to a restart",
    );
  });

  it("describes one world across the goal, the contract and the environment", () => {
    assert.equal(contract.goal_id, goal.id, "the contract is filed against a different goal");
    assert.equal(goal.acceptance, "acceptance.yaml", "the goal points at a contract that is not here");
    assert.equal(goal.environment, "environment.yaml", "the goal points at an environment that is not here");
    assert.equal(environment.adapter, ADAPTER, `the environment does not name the ${ADAPTER} adapter`);
  });

  it("states every pointer the adapter requires, and no browser reading", () => {
    const world = findWorld(ADAPTER);
    assert.ok(world, `no world is registered as ${ADAPTER}`);

    for (const requirement of world.requires) {
      const value = pointer(environment, requirement.field);
      assert.ok(
        value !== undefined && value !== null,
        `the ${ADAPTER} world requires ${requirement.field}, and this environment does not state it: ` +
          `${requirement.question}`,
      );
    }

    assert.equal(
      environment.url,
      null,
      "a world with an address is asked for a browser, and this contract's criteria are all " +
        "extension-host readings",
    );
    const browser = namedValidators.filter((name) => name.startsWith("playwright."));
    assert.deepEqual(browser, [], `the contract asks the browser family (${browser.join(", ")}) for a reading`);
  });

  it("reads only environment names the adapter declares", () => {
    const program = read(`${DEMO}/app/provision.mjs`);
    const adapter = read("adapters/sim-vscode/sim-vscode-environment.ts");
    const used = new Set(program.match(/VERIDIAN_VSCODE_[A-Z_]+/g) ?? []);
    const declared = new Set(adapter.match(/VERIDIAN_VSCODE_[A-Z_]+/g) ?? []);

    assert.ok(used.size > 0, "the application reads no environment name at all");
    const undeclared = [...used].filter((name) => !declared.has(name));
    assert.deepEqual(
      undeclared,
      [],
      `the application reads ${undeclared.join(", ")}, which the ${ADAPTER} adapter never sets - so ` +
        `the program would take its own fallback and every criterion would judge that instead`,
    );
  });

  it("assembles the readiness count from the array the program wrote", () => {
    const program = read(`${DEMO}/app/provision.mjs`);
    const ready = record(environment.start).readyPattern;
    assert.equal(typeof ready, "string", "the environment declares no readiness pattern");

    assert.match(
      program,
      /\$\{String\(steps\.length\)\}/,
      "the readiness line no longer counts the array the loop above wrote",
    );
    assert.doesNotMatch(
      program,
      /provisioned: \d/,
      "the readiness line holds a literal figure, which is free to disagree with the loop above it",
    );
    assert.ok(
      String(ready).includes("provisioned: "),
      `the environment waits for "${String(ready)}" while the program prints its own sentence`,
    );
  });

  it("ignores both trees it generates, because a generated tree is not source", () => {
    const rules = read(".gitignore")
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter((line) => line.length > 0 && !line.startsWith("#"));

    // The staged artifact and the sandbox the world rebuilds. `demo.ts` removes the first on exit and
    // `--keep-staged` deliberately leaves it, which is exactly the case this rule exists for.
    for (const generated of [`${DEMO}/app/extension/`, `${DEMO}/app/sandbox/`]) {
      assert.ok(
        rules.some((rule) => generated.startsWith(rule.replace(/\*+/g, "").replace(/^\//, ""))),
        `${generated} is not ignored, so the next \`git add .\` would commit a tree this demo ` +
          "generated - which is the defect `extension/vscode/out/` already paid for",
      );
    }
  });
});
