// A provisioning program whose subject is the Veridian Cockpit itself.
//
// It behaves exactly as every other application in this repository behaves: it prints command vectors
// on stdout, one JSON array per line, and it prints a readiness line on stderr as the last thing it
// does. It does not decide whether the Cockpit works - the world's records are what decide that.
//
// It also seeds the bundle the Cockpit reads, because the command under test is `veridian.showResult`
// and a reporter with nothing to report renders nothing. Seeding it is the *scenario* the criterion
// needs, not a claim about the outcome.
//
// The extension directory beside this file is NOT committed: `demo.ts` copies it out of
// `extension/vscode` before the run and removes it afterwards. It cannot be committed, because what
// this world has to judge is the compiled artifact rather than a source tree, and the compiled tree is
// regenerated by a build.

import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

/** The env names this application reads. The adapter declares the same names; a test intersects them. */
export const VSCODE_ENV = {
  sandbox: "VERIDIAN_VSCODE_SANDBOX",
  workspace: "VERIDIAN_VSCODE_WORKSPACE",
  host: "VERIDIAN_VSCODE_HOST",
  apiVersion: "VERIDIAN_VSCODE_API_VERSION",
};

/** The directory the Cockpit's own manifest sits in, relative to the application directory. */
export const EXTENSION_DIR = "extension";

/** The name the Cockpit's manifest publishes under. The world installs it under this name. */
export const APPLICATION = "veridian-cockpit";

/**
 * A run result for the Cockpit to render.
 *
 * Every value here is a constant this file chose, so a criterion that asserts on the rendered text is
 * asserting on the Cockpit's formatting rather than on whatever run happened to be on disk. `iteration`
 * is 5 rather than 1 so that a reader can see the number travelled through the renderer.
 */
const RESULT = {
  run_id: "run-20260101-000000-c0c0c0",
  verdict: "PASS",
  state: "COMPLETED",
  iteration: 5,
  criteria: [
    { criterion_id: "AC-001", status: "PASS", mandatory: true, message: "the world answered" },
    { criterion_id: "AC-002", status: "PASS", mandatory: true, message: "the extension activated" },
    { criterion_id: "AC-003", status: "PASS", mandatory: true, message: "the report was rendered" },
  ],
  reasons: ["3/3 mandatory criteria passed, environment valid, no safety violation, evidence complete."],
  iterations: [{ iteration: 5, verdict: "PASS", passed: 3, failed: 0, undecided: 0, note: "" }],
  evidence: { complete: true },
};

const say = (stream, line) => {
  process[stream].write(`${line}\n`);
};

/** One command vector. This is the only thing this program is permitted to put on stdout. */
const vector = (...argv) => {
  say("stdout", JSON.stringify(argv));
};

const workspace = process.env[VSCODE_ENV.workspace] ?? "";
const stateDir = join(workspace, ".veridian");

await mkdir(stateDir, { recursive: true });
await writeFile(
  join(stateDir, "latest-result.json"),
  `${JSON.stringify(RESULT, null, 2)}\n`,
  "utf8",
);
await writeFile(
  join(stateDir, "latest-failure.md"),
  "# Veridian failure report\n\n3 of 3 mandatory criteria passed.\n",
  "utf8",
);

/**
 * The actions this run asks the world to perform.
 *
 * `install` names the *manifest*, not a directory, because that is what a real client is given and the
 * world reads the extension's own source rather than a copy of it. `activate` gets a host process of
 * its own so that activation is judged on a host this run started. The two `invoke` lines are the
 * subject: both are commands the Cockpit declares, and both are *viewer* commands - they read a bundle
 * and reveal a file, so neither changes the world and a defect in one is invisible to the other.
 *
 * Nothing here invokes `veridian.metrics`, `veridian.validate` or `veridian.clarify`: those resolve a
 * CLI path, and this world has no CLI installed. Invoking one would produce a "Veridian not found"
 * error message, which is a true reading about a workspace with no checkout in it and not a reading
 * about the Cockpit.
 */
const steps = [
  ["install", `${EXTENSION_DIR}/package.json`],
  ["activate"],
  ["invoke", "veridian.showResult"],
  ["invoke", "veridian.openFailure"],
];

for (const step of steps) vector(...step);

// Last, on stderr, and a *claim about the work* rather than an instruction: the world reads it to
// decide that provisioning finished and reads nothing else from it. The count is assembled from the
// array this program actually wrote, because a literal here could disagree with the loop above.
say("stderr", `${APPLICATION} provisioned: ${String(steps.length)} commands`);
