/**
 * The environment layer.
 *
 * `types` declares the contracts, `load` decodes a definition into a plan, and `manager` is the only
 * thing allowed to move that plan through the lifecycle. Adapters implement `EnvironmentAdapter`;
 * they are deliberately absent from this barrel, because importing one from the Core would make the
 * Core depend on a particular world — which is the boundary *"VS Code ≠ Veridian"* draws for every
 * surface, not just the editor.
 */

export {
  finalizeEnvironment,
  loadEnvironmentDocument,
  probeUrl,
} from "./load.ts";

export {
  ENVIRONMENT_STATES,
  EnvironmentManager,
  type EnvironmentFailure,
  type EnvironmentManagerOptions,
  type EnvironmentReady,
  type EnvironmentState,
  type EnvironmentTransition,
  type PrepareResult,
  type ResetResult,
} from "./manager.ts";

export {
  RESET_STRATEGIES,
  type ApplicationStart,
  type ArtifactKind,
  type BoundaryEnforcement,
  type BoundaryPolicy,
  type BoundaryReport,
  type BrowserPolicy,
  type CloudPlan,
  type ClusterPlan,
  type ContainerPlan,
  type DataPlan,
  type EnvironmentAdapter,
  type EnvironmentDefinitionShape,
  type EnvironmentPlan,
  type EvidenceArtifact,
  type HealthPolicy,
  type HealthProbe,
  type HealthReport,
  type MobilePlan,
  type Observation,
  type ObservationRequest,
  type OsPlan,
  type PosixPlan,
  type ProcessPlan,
  type ResetStrategy,
} from "./types.ts";

export {
  CLOUD_ACTIONS,
  CLOUD_ACTION_NAMES,
  CLOUD_CALL_RESULTS,
  CLOUD_CALL_SOURCES,
  CLOUD_ENCRYPTION_ALGORITHMS,
  CLOUD_METER_KEYS,
  CLOUD_OBSERVATION_KIND,
  CLOUD_PLACEHOLDER_VALUES,
  CLOUD_POLICY_EFFECTS,
  CLOUD_REF_KINDS,
  CLOUD_SIMULATED_SURFACES,
  CLOUD_VERSIONING_STATES,
  bucketNamed,
  cloudCallsOf,
  cloudRefSpelling,
  decisionFor,
  isCloudObservationData,
  meterValue,
  objectAt,
  principalNamed,
  principalProblem,
  queueNamed,
  refName,
  renderBucket,
  renderDecision,
  renderObject,
  renderPolicy,
  renderPrincipal,
  renderQueue,
  renderCloudRef,
  renderSecret,
  resolveCloudAccessRef,
  resolveCloudRef,
  secretNamed,
  type CloudAccessRef,
  type CloudAction,
  type CloudBucketReading,
  type CloudCallRecord,
  type CloudCallResult,
  type CloudCallSource,
  type CloudDecisionReading,
  type CloudEncryptionAlgorithm,
  type CloudMeterKey,
  type CloudMeterReading,
  type CloudObjectReading,
  type CloudObservationData,
  type CloudPolicyEffect,
  type CloudPolicyStatement,
  type CloudPrincipalReading,
  type CloudQueueReading,
  type CloudRef,
  type CloudSecretReading,
  type CloudSecretVersion,
  type CloudSimulatedSurface,
  type CloudTargetResult,
  type CloudVersioningState,
} from "./cloud-observation.ts";

export {
  CONTAINER_ACTIONS,
  CONTAINER_ACTION_RESULTS,
  CONTAINER_CLIENTS,
  CONTAINER_HEALTH_STATES,
  CONTAINER_MOUNT_KINDS,
  CONTAINER_OBSERVATION_KIND,
  CONTAINER_PLATFORMS,
  CONTAINER_PORT_PROTOCOLS,
  CONTAINER_REF_KINDS,
  CONTAINER_SIMULATED_SURFACES,
  CONTAINER_STATES,
  containerCallsOf,
  containerNamed,
  containerRefSpelling,
  imageOf,
  imageTagged,
  isContainerAction,
  isContainerObservationData,
  logsOf,
  renderCall,
  renderContainer,
  renderHealth,
  renderImage,
  renderLimit,
  renderMount,
  renderPort,
  renderUser,
  resolveContainerRef,
  type ContainerAction,
  type ContainerActionResult,
  type ContainerCallRecord,
  type ContainerClient,
  type ContainerHealthReading,
  type ContainerHealthState,
  type ContainerImageReading,
  type ContainerInstanceReading,
  type ContainerLogReading,
  type ContainerMountKind,
  type ContainerMountReading,
  type ContainerObservationData,
  type ContainerPlatform,
  type ContainerPortProtocol,
  type ContainerPortReading,
  type ContainerRef,
  type ContainerResourceReading,
  type ContainerRuntimeReading,
  type ContainerSimulatedSurface,
  type ContainerState,
  type ContainerTargetResult,
} from "./container-observation.ts";

export {
  PROCESS_APPLICATION,
  PROCESS_COMMAND_STATES,
  PROCESS_FILE_KINDS,
  PROCESS_OBSERVATION_KIND,
  commandAbsentReason,
  commandAt,
  commandSelectorOf,
  fileAt,
  isProcessObservationData,
  processPath,
  renderArgv,
  renderCommand,
  renderExit,
  renderFile,
  renderHost,
  renderStream,
  type ProcessCommandRecord,
  type ProcessCommandState,
  type ProcessFileKind,
  type ProcessFileReading,
  type ProcessObservationData,
  type ProcessStreamReading,
} from "./process-observation.ts";

export {
  DATA_METER_KEYS,
  DATA_OBSERVATION_KIND,
  DATA_REF_NOUNS,
  DATA_REQUEST_RESULTS,
  DATA_SIMULATED_SURFACES,
  dataCommittedAt,
  dataGroupNamed,
  dataMemberNamed,
  dataMeterValue,
  dataPartitionAt,
  dataRecordAt,
  dataTopicNamed,
  isDataObservationData,
  parseDataRef,
  renderCommitted,
  renderGroup,
  renderMember,
  renderMeter,
  renderNode,
  renderNodeIdentity,
  renderPartition,
  renderRecord,
  renderRequest,
  renderSimulatedSurfaces,
  renderTopic,
  resolveDataRef,
  type DataCommittedOffsetReading,
  type DataGroupMemberReading,
  type DataGroupReading,
  type DataHeaderReading,
  type DataMeterKey,
  type DataMeterReading,
  type DataNodeReading,
  type DataObservationData,
  type DataPartitionReading,
  type DataRecordReading,
  type DataRef,
  type DataRefNoun,
  type DataRequestRecord,
  type DataRequestResult,
  type DataSimulatedSurface,
  type DataTopicReading,
} from "./data-observation.ts";
